# Server configuration - HTTPS only
server.port=13224
server.ssl.key-store=classpath:tomcat.keystore
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat

server.ssl.trust-store=classpath:truststore.jks
server.ssl.trust-store-password=password
server.ssl.trust-store-type=JKS


# Service 1 URL
service1.url=https://localhost:13223

# Application name
spring.application.name=route-service-2
